### PR TITLE
added more informations on the s message

### PR DESCRIPTION
**Pull request by Zergie**

### CODE REVIEW

**Comment by Bouni** [comment]
Hi Zergie.

thanks for your effort in this project! 
Please change the name of the file "S-Message" to "S-Message.md" so that i can merge it.

**Comment by Zergie** [comment]
Hi Bouni,
i have renamed "S-Message" to "S-Message.md" in 32ef45213d97a70856528b7ebbcd56033a69ae73 , so did you in 801d721c289a2fbe7bddbd8078842499d606ea2f .
I am new to this, but i think thats the problem.

**Comment by Bouni** [comment]
Hmmm, strange. I will merge it manually, give me a second.

**Comment by Bouni** [comment]
Ok, done. I hope i got everything right! I'm also not very used to git ;-)

**Pull request merged**
